### ISSUE TITLE
missing talkbridge_service_account.json

### ISSUE THREAD

**Issue by flutter-painter** [MarekRudzki/TalkBridge#8]
When trying to translate I get his error : 
"Unhandled Exception: Unable to load asset: "assets/talkbridge_service_account.json".
The asset does not exist or has empty data."

I presume I am meant to replace this file with my own. Could you please provide a hint in the readme on what kind of file is expected here ? Is it the .json from firebase ?

**Comment by MarekRudzki** [comment]
Hi!
Indeed you have to replace "talkbridge_service_account.json" file with your own. To do so create a [Google Cloud](https://console.cloud.google.com/) account and activate the Speech Api. Next you should get the Json file, rename it as "talkbridge_service_account.json" and save to assets folder.
